CREATE TABLE `kategoria` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`nazwa` VARCHAR(30) NOT NULL,
	`id_parent` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`id`),
	UNIQUE INDEX `Nazwa_UNIQUE` (`nazwa`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=13
;
